# Configuration for probot-no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 14

# Label requiring a response
responseRequiredLabel: awaiting response

# Comment to post when closing an Issue for lack of response. Set to `false` to disable
closeComment: >
  This issue has been automatically closed because there has been no response
  from the original author within 14 days. Feel free to reopen this issue if
  you have more details that may help investigate the problem further.
